#pragma once

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 1000

#define BASE_BLOCK_SIZE 50

#define GRAVITY   981.0f
#define SPEED_STRAIGHT  200.0f
#define JUMP_HEIGHT  200.0f
#define SECOND_JUMP_HEIGHT  150.0f
#define SECOND_JUMP_DELAY  0.5f

#define BOUNCE_UP_ON_ENEMY 150.0f
#define BOUNCE_SIDE_ON_ENEMY 100.0f


#define MOVING_OBJECT_BASE_SPEED 200.0f
#define MOVING_OBJECT_BASE_DAMAGE 50


#define BULLET_MAX_RANGE 1100.0f
#define BULLET_VELOCITY_X 600.0f
#define BULLET_DELAY 0.8f
#define BULLET_DAMGE_LOSS 10

#define EXPLOSIVE_FIRE_BALL_DELAY 5.0f
#define EXPLOSIVE_FIRE_BALL_VELOCITY_X 250.0f
#define EXPLOSIVE_FIRE_BALL_MAX_HEIGHT 50.0f
#define EXPLOSIVE_FIRE_BALL_DAMAGE 50.0f
#define EXPLOSION_SIZE 80
#define EXPLOSIVE_FIRE_BALL_MAX_RANGE 4.0f
#define EXPLOSION_DAMAGE 50;

#define IMMUNITY_TIME 1.5f

#define BASE_ENEMY_HEALTH 300
#define BASE_ENEMY_TOUCH_DAMAGE 100


#define PATROLING_ENEMY_BASE_SPEED 200.0f

#define JUMPING_ENEMY_BASE_JUMP_HEIGHT 200.0f

#define CHARGING_ENEMY_BASE_SPEED 400.0f
#define CHARGING_ENEMY_DISTANCE_TRIGGER 400

#define SMALL_POTION_HP 100
#define SMALL_POTION_MANA 50